name: CI

concurrency:
  group: release-${{ github.ref_name }}-${{ github.event_name }}
  cancel-in-progress: ${{ !startsWith(github.ref, 'refs/tags/') }}

on:
  pull_request:
    branches:
      - master

jobs:
  ci:
    name: Continuous Integration (CI)
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      actions: 'read'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'master'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check formatting
        run: npx nx format:check

      - name: Lint, test, and build
        run: npx nx affected -t lint,test,build --parallel=3
