name: Chart Version Check

on:
  pull_request:
    branches: [master]
    paths:
      - 'k8s/charts/operator/**'

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install yq
        run: |
          wget https://github.com/mikefarah/yq/releases/download/v4.34.2/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Check version bump
        run: |
          # Get the version from the PR branch
          if [ ! -f "k8s/charts/operator/Chart.yaml" ]; then
            echo "Chart.yaml does not exist in PR branch"
            exit 0
          fi
          NEW_VERSION=$(yq e '.version' k8s/charts/operator/Chart.yaml)

          # Try to get the version from the base branch
          git checkout origin/${{ github.base_ref }}
          if [ ! -f "k8s/charts/operator/Chart.yaml" ]; then
            echo "Chart.yaml does not exist in base branch, skipping version check"
            exit 0
          fi

          OLD_VERSION=$(yq e '.version' k8s/charts/operator/Chart.yaml)

          if [ "$NEW_VERSION" = "$OLD_VERSION" ]; then
            echo "Error: Chart version was not bumped. Please update the version in Chart.yaml"
            exit 1
          fi

          if ! printf '%s\n' "$OLD_VERSION" "$NEW_VERSION" | sort -V -C; then
            echo "Error: New version ($NEW_VERSION) is not higher than the old version ($OLD_VERSION)"
            exit 1
          fi
