name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Check and copy operator chart
        id: copy-chart
        run: |
          if [ -d "k8s/charts/operator" ] && [ -f "k8s/charts/operator/Chart.yaml" ]; then
            mkdir -p charts
            cp -r k8s/charts/operator/* charts/
            echo "has_chart=true" >> $GITHUB_OUTPUT
          else
            echo "No operator chart found to release"
            echo "has_chart=false" >> $GITHUB_OUTPUT
          fi

      - name: Add repositories
        if: steps.copy-chart.outputs.has_chart == 'true'
        run: |
          if [ -d "charts" ]; then
            for dir in $(ls -d charts/* 2>/dev/null || true); do
              if [ -d "$dir" ] && [ -f "$dir/Chart.yaml" ]; then
                helm dependency list $dir 2> /dev/null | tail +2 | head -n -1 | awk '{ print "helm repo add " $1 " " $3 }' | while read cmd; do $cmd; done
              fi
            done
          fi

      - name: Build chart dependencies
        if: steps.copy-chart.outputs.has_chart == 'true'
        run: |
          if [ -d "charts" ]; then
            for dir in charts/*/; do
              if [ -d "$dir" ] && [ -f "$dir/Chart.yaml" ]; then
                (cd "$dir" && helm dependency build)
              fi
            done
          fi

      - name: Run chart-releaser
        if: steps.copy-chart.outputs.has_chart == 'true'
        uses: helm/chart-releaser-action@v1.6.0
        with:
          config: './.github/configs/cr.yaml'
        env:
          CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          CR_SKIP_EXISTING: true
